name: carcare
description: Car Care Garage App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.1
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  firebase_storage: ^12.3.7
  http: ^1.1.0
  intl: ^0.20.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/AppBar48.png
    - assets/images/car_image.png
    - assets/images/hi.png
    - assets/images/test.png
    - assets/images/home_screenfix.png
    - assets/images/home.png
    - assets/images/logo.png
    - assets/images/logo192.png
    - assets/images/selectpic.png
    - assets/images/robot.png
    - assets/images/splash_screenlogo.png
    - assets/images/splash200.png
    - assets/images/welcom_screenlogo.png
    - assets/images/welcom100.png
  
  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Regular.ttf
        - asset: assets/fonts/Sen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sen-Medium.ttf
          weight: 300